version: "3.3"

services:

  backend_app:
    ports:
      - "80:80"
    restart: on-failure
    build: ./


  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: " "
      POSTGRES_DB: "MyLittleYandexDisk"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - .sql_scripts:/docker-entrypoint-initdb.d

volumes:
  db-data:
